# -*- coding: utf-8 -*-
"""Web_model_work.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pl0vu4q7sgFCaDzJ-jGedTvAMUi5uPmz

・食べ物の画像を入力

・その食べ物を分類し、その食べ物のレシピのWeb記事を持ってくる。

・LLMにする場合、単語を一つ抽出する出力形式に合わせる必要があるため、プロンプトで「一単語で出力して」と書く。

・Web記事の検索については、志木高でもらったpythonスクレイピングの本を参考に

・Webページの作り方はここを参考に(https://qiita.com/oyngtmhr/items/433974829015abac753c)
"""

import requests
import PIL
from datetime import datetime
import os
import base64
from io import BytesIO
from urllib.parse import quote
from bs4 import BeautifulSoup
from PIL import Image

from flask import Flask, render_template, request, redirect, url_for, abort

#device= "cuda" if torch.cuda.is_available() else "cpu"

app = Flask(__name__)

HF_TOKEN = os.environ.get("HF_TOKEN")
MODEL_ID = "llava-hf/llava-1.5-7b-hf"
# Hugging FaceのChat Completions互換エンドポイント
API_URL = "https://api-inference.huggingface.co/v1/chat/completions"

def analyze_image_with_llava(pil_image: Image.Image) -> str:
    # 1. PIL画像をBase64形式の文字列に変換
    buffered = BytesIO()
    pil_image.save(buffered, format="JPEG")
    img_str = base64.b64encode(buffered.getvalue()).decode("utf-8")
    image_data_url = f"data:image/jpeg;base64,{img_str}"

    # 2. ヘッダーとプロンプト（メッセージ構造）の構築
    headers = {
        "Authorization": f"Bearer {HF_TOKEN}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "model": MODEL_ID,
        "messages": [
            {
                "role": "user",
                "content": [
                    {"type": "image_url", "image_url": {"url": image_data_url}},
                    {"type": "text", "text": "この画像の食材は何？ひらがなかカタカナで、1単語で教えて。"}
                ]
            }
        ],
        "max_tokens": 30
    }

    # 3. Hugging Faceへ送信
    response = requests.post(API_URL, headers=headers, json=payload)
    response_data = response.json()
    
    if response.status_code != 200:
        raise Exception(f"API Error: {response_data}")

    # レスポンスから解析結果のテキストを抽出
    return response_data["choices"][0]["message"]["content"].strip()

def search_get_recipe(keyword):
    """Playwrightの代わりにrequests + BeautifulSoupを使って高速・軽量にスクレイピング"""
    encoded_keyword = quote(keyword)
    search_url = f"https://cookpad.com/jp/search/{encoded_keyword}"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    }

    url_list = []
    title_list = []
    full_url_list=[]
    

    try:
        # 検索結果ページの取得
        res = requests.get(search_url, headers=headers, timeout=5)
        soup = BeautifulSoup(res.text, "html.parser")

        recipe_links = soup.select('a[href*="/jp/recipes/"]')

        for link in recipe_links:
            href = link.get("href")
            if href and href not in url_list:
                url_list.append(href)
            if len(url_list) >= 5:
                break

        for href in url_list:
            full_url = (
                "https://cookpad.com" + href if href.startswith("/") else href
            )

            # 各レシピページのタイトル取得
            r = requests.get(full_url, headers=headers, timeout=5)
            s = BeautifulSoup(r.text, "html.parser")

            h1 = s.find("h1")
            title = h1.get_text(strip=True) if h1 else "クックパッド レシピ"

            full_url_list.append(full_url)
            title_list.append(title)

    except Exception as e:
        print(f"Scraping error: {e}")

    return full_url_list, title_list


@app.route("/",methods=["GET","POST"])
def upload_file():
  if request.method == "GET":
    return render_template("cook_index.html")
  if request.method == "POST":
    f=request.files["file"]
    current_filepath="static/" + datetime.now().strftime("%Y%m%d%H%M%S") + ".png"
    base_dir=os.path.dirname(__file__)
    filepath=os.path.join(base_dir,current_filepath)
    f.save(filepath)
    image=PIL.Image.open(filepath).convert("RGB")

    output = analyze_image_with_llava(image)

    recipe_url , recipe_title = search_get_recipe(output)

    # エラー防止のため、足りない分は空文字で埋める
    while len(recipe_url) < 5:
        recipe_url.append("")
        recipe_title.append("")

    # 修正: index_html -> index.html
    return render_template("cook_index.html" ,
                           filepath=current_filepath ,
                           result=output ,
                           recipe_url=recipe_url,
                           recipe_title=recipe_title,)

if __name__ == "__main__":
    app.run(debug=True)
