# -*- coding: utf-8 -*-
"""Web_model_work.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pl0vu4q7sgFCaDzJ-jGedTvAMUi5uPmz

・食べ物の画像を入力

・その食べ物を分類し、その食べ物のレシピのWeb記事を持ってくる。

・LLMにする場合、単語を一つ抽出する出力形式に合わせる必要があるため、プロンプトで「一単語で出力して」と書く。

・Web記事の検索については、志木高でもらったpythonスクレイピングの本を参考に

・Webページの作り方はここを参考に(https://qiita.com/oyngtmhr/items/433974829015abac753c)
"""

import requests
import PIL
from datetime import datetime
import transformers
import torch
import os

from flask import Flask, render_template, request, redirect, url_for, abort
from playwright.sync_api import sync_playwright
from urllib.parse import quote

#device= "cuda" if torch.cuda.is_available() else "cpu"
model=transformers.LlavaForConditionalGeneration.from_pretrained("llava-hf/llava-1.5-7b-hf",device_map="auto",torch_dtype=torch.float16,low_cpu_mem_usage=True)
processor=transformers.LlavaProcessor.from_pretrained("llava-hf/llava-1.5-7b-hf",device_map="auto",torch_dtype=torch.float16,low_cpu_mem_usage=True)
prompt="USER:<image>\nこの画像の食材は何？ひらがなかカタカナで、1単語で教えて。\nASSISTANT:"

app = Flask(__name__)

def search_get_recipe(keyword):
  with sync_playwright() as p:
    browser=p.chromium.launch(headless=True)
    page=browser.new_page()
    encoded_keyword = quote(keyword)
    search_url = f"https://cookpad.com/jp/search/{encoded_keyword}"
    page.goto(search_url)
    page.wait_for_load_state("networkidle")
    recipe_links = page.locator('a[href*="/jp/recipes/"]').all()

    url_list=[]
    title_list=[]

    for link in recipe_links:
      href = link.get_attribute("href")
      if href not in url_list: # 重複を除外
          url_list.append(href)
      if len(url_list) >= 6:
        url_list=url_list[1:6]
        break

    full_url_list = []
    for href in url_list:
      # 相対パスの場合はドメインを追加
      full_url = "https://cookpad.com" + href if href.startswith("/") else href
      full_url_list.append(full_url)
      page.goto(full_url)
      try:
          # h1 が表示されるのを最大 5秒間 待つ
          page.wait_for_selector("h1", timeout=5000)
          title = page.locator("h1").first.inner_text()
      except Exception:
          # h1 が取得できなかった場合は、ブラウザタブのタイトルからレシピ名を取得
          title = page.title().split(" | ")[0]
      title_list.append(title)

    browser.close()
    return full_url_list , title_list


@app.route("/",methods=["GET","POST"])
def upload_file():
  if request.method == "GET":
    return render_template("cook_index.html")
  if request.method == "POST":
    f=request.files["file"]
    current_filepath="static/" + datetime.now().strftime("%Y%m%d%H%M%S") + ".png"
    base_dir=os.path.dirname(__file__)
    filepath=os.path.join(base_dir,current_filepath)
    f.save(filepath)
    image=PIL.Image.open(filepath).convert("RGB")

    # kwargsで明示的に渡し、モデルのdtypeに合わせる
    inputs=processor(text=prompt, images=image, return_tensors="pt").to(model.device, torch.float16)

    outputs=model.generate(
        **inputs,
        do_sample=False,
        max_new_tokens=30,
        use_cache=True,
        eos_token_id=processor.tokenizer.eos_token_id,
        pad_token_id=processor.tokenizer.eos_token_id,
    )

    # ASSISTANT以降の出力テキストを抽出
    decoded_output=processor.decode(outputs[0], skip_special_tokens=True)
    output = decoded_output.split("ASSISTANT:")[-1].strip()

    recipe_url , recipe_title = search_get_recipe(output)

    # エラー防止のため、足りない分は空文字で埋める
    while len(recipe_url) < 5:
        recipe_url.append("")
        recipe_title.append("")

    # 修正: index_html -> index.html
    return render_template("cook_index.html" ,
                           filepath=current_filepath ,
                           result=output ,
                           recipe_url=recipe_url,
                           recipe_title=recipe_title,)

if __name__ == "__main__":
    app.run(debug=True)